#!/bin/bash
# Cheat Sheet - Comandos más frecuentes

echo "═══════════════════════════════════════════════════════════════════════"
echo "  Costa Rica Trip Packages - Comandos Rápidos"
echo "═══════════════════════════════════════════════════════════════════════"
echo ""

# Desarrollo
echo "🚀 DESARROLLO LOCAL"
echo "─────────────────────────────────────────────────────────────────────"
echo "# Terminal 1: Servidor Laravel"
echo "  php artisan serve"
echo ""
echo "# Terminal 2: Vite (HMR activado)"
echo "  npm run dev"
echo ""
echo "Accede a:"
echo "  - http://localhost:8000/           (Landing Blade)"
echo "  - http://localhost:8000/react-app  (React App)"
echo ""

# Build
echo "📦 PRODUCCIÓN"
echo "─────────────────────────────────────────────────────────────────────"
echo "# Generar build estático"
echo "  npm run build"
echo ""
echo "# Verificar build"
echo "  ls -la public/build/"
echo ""

# Laravel Artisan
echo "🔨 COMANDOS ARTISAN ÚTILES"
echo "─────────────────────────────────────────────────────────────────────"
echo "# Crear modelo con migración"
echo "  php artisan make:model Package -m"
echo ""
echo "# Crear controlador"
echo "  php artisan make:controller PackageController"
echo ""
echo "# Crear API controller"
echo "  php artisan make:controller Api/PackageController --api"
echo ""
echo "# Ejecutar migraciones"
echo "  php artisan migrate"
echo ""
echo "# Crear migración"
echo "  php artisan make:migration create_packages_table"
echo ""
echo "# Limpiar caché"
echo "  php artisan optimize:clear"
echo ""

# npm
echo "📦 COMANDOS NPM"
echo "─────────────────────────────────────────────────────────────────────"
echo "# Instalar dependencias"
echo "  npm install"
echo ""
echo "# Agregar nuevo paquete"
echo "  npm install nombre-paquete --save"
echo ""
echo "# Actualizar paquetes"
echo "  npm update"
echo ""
echo "# Ver vulnerabilidades"
echo "  npm audit"
echo ""
echo "# Arreglar vulnerabilidades"
echo "  npm audit fix"
echo ""

# Estructura
echo "📁 CREAR NUEVOS COMPONENTES"
echo "─────────────────────────────────────────────────────────────────────"
echo "# Nuevo componente React"
echo "  touch resources/js/components/MiComponente.jsx"
echo ""
echo "# Nueva vista Blade"
echo "  touch resources/views/mi-pagina.blade.php"
echo ""
echo "# Nuevo CSS para componente"
echo "  touch resources/js/components/MiComponente.css"
echo ""

# Deploy
echo "🌐 DEPLOY A HOSTINGER"
echo "─────────────────────────────────────────────────────────────────────"
echo "# Paso 1: Build local"
echo "  npm run build"
echo ""
echo "# Paso 2: Subir via FTP (carpeta public/ completa)"
echo ""
echo "# Paso 3: SSH al servidor"
echo "  ssh usuario@tudominio.com"
echo ""
echo "# Paso 4: Instalar dependencias PHP"
echo "  composer install --no-dev"
echo ""
echo "# Paso 5: Generar clave"
echo "  php artisan key:generate"
echo ""
echo "# Paso 6: Permisos"
echo "  chmod 755 storage/"
echo "  chmod 755 bootstrap/cache/"
echo ""

# Debugging
echo "🐛 DEBUGGING"
echo "─────────────────────────────────────────────────────────────────────"
echo "# Ver logs Laravel"
echo "  tail -f storage/logs/laravel.log"
echo ""
echo "# Tinker (consola interactiva)"
echo "  php artisan tinker"
echo ""
echo "# Ver variables de entorno"
echo "  php artisan env"
echo ""

# Limpieza
echo "🧹 LIMPIAR Y OPTIMIZAR"
echo "─────────────────────────────────────────────────────────────────────"
echo "# Limpiar caché de Laravel"
echo "  php artisan optimize:clear"
echo ""
echo "# Limpiar caché de Vite"
echo "  rm -rf node_modules/.vite"
echo ""
echo "# Reinstalar todo"
echo "  rm -rf node_modules package-lock.json"
echo "  npm install"
echo ""

echo "═══════════════════════════════════════════════════════════════════════"
echo "✨ Para más info, ve a:"
echo "   - ESTRUCTURA.md"
echo "   - README_SETUP.md"
echo "   - https://laravel.com/docs"
echo "   - https://vitejs.dev"
echo "═══════════════════════════════════════════════════════════════════════"
