#!/bin/bash

# Colores
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}"
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║         🧪 GUÍA: CÓMO PROBAR EL HELLO WORLD EN REACT 🧪        ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

echo -e "${BLUE}PASO 1: Abre dos terminales (o usa tmux)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo -e "${YELLOW}Terminal 1 - Servidor Laravel:${NC}"
echo "  \$ cd /home/elizabeth/costaricatrippackages"
echo "  \$ php artisan serve"
echo ""
echo "  Espera a ver:"
echo "  ${GREEN}Laravel development server started: http://127.0.0.1:8000${NC}"
echo ""

echo -e "${YELLOW}Terminal 2 - Vite Development Server:${NC}"
echo "  \$ cd /home/elizabeth/costaricatrippackages"
echo "  \$ npm run dev"
echo ""
echo "  Espera a ver:"
echo "  ${GREEN}VITE v5.4.21 ready in XXX ms${NC}"
echo "  ${GREEN}➜ Local: http://localhost:5173/${NC}"
echo ""

echo -e "${BLUE}PASO 2: Abre tu navegador web${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "${GREEN}Opción A: Landing Page (Blade puro - sin React)${NC}"
echo "  URL: ${YELLOW}http://localhost:8000/${NC}"
echo "  Qué verás:"
echo "    ✓ Landing profesional con gradiente verde"
echo "    ✓ 3 paquetes turísticos"
echo "    ✓ Características del servicio"
echo "    ✓ Botones de reserva"
echo ""

echo -e "${GREEN}Opción B: React App (Hello World interactivo)${NC}"
echo "  URL: ${YELLOW}http://localhost:8000/react-app${NC}"
echo "  Qué verás:"
echo "    ✓ Fondo con gradiente púrpura-violeta"
echo "    ✓ Título: '¡Hola desde React! 🚀'"
echo "    ✓ Descripción: 'Integración exitosa de React + Vite en Laravel'"
echo "    ✓ Contador interactivo (empieza en 0)"
echo ""

echo -e "${BLUE}PASO 3: Prueba los 3 Botones${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo -e "${YELLOW}Botón 1 - INCREMENTAR (color verde)${NC}"
echo "  Acción: Haz clic en 'Incrementar'"
echo "  Resultado: El contador aumenta de 0 a 1, 2, 3... etc"
echo "  Prueba: Hazlo 5 veces → deberías ver 5"
echo ""

echo -e "${YELLOW}Botón 2 - DECREMENTAR (color naranja)${NC}"
echo "  Acción: Haz clic en 'Decrementar'"
echo "  Resultado: El contador disminuye"
echo "  Prueba: Si está en 5, haz clic → deberías ver 4, 3, 2, 1, 0, -1"
echo ""

echo -e "${YELLOW}Botón 3 - REINICIAR (color rojo)${NC}"
echo "  Acción: Haz clic en 'Reiniciar'"
echo "  Resultado: El contador vuelve a 0"
echo "  Prueba: Sube a 10, luego reinicia → debería ser 0"
echo ""

echo -e "${BLUE}PASO 4: Verifica otras secciones${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo -e "${YELLOW}Sección: ¿Por Qué Elegirnos?${NC}"
echo "  • Muestra 6 características con iconos"
echo "  • Incluye: Vuelos, Hoteles, Tours, Precio, Atención, Reserva"
echo ""

echo -e "${YELLOW}Sección: Nuestros Paquetes${NC}"
echo "  • Paquete Playas: \$1,299"
echo "  • Paquete Aventura: \$1,799"
echo "  • Paquete Naturaleza: \$1,499"
echo ""

echo -e "${YELLOW}Sección: Stack Tecnológico${NC}"
echo "  🐘 PHP 8.1"
echo "  🌱 Laravel"
echo "  ⚛️ React 19"
echo "  ⚡ Vite"
echo ""

echo -e "${BLUE}PASO 5: Prueba Hot Module Reload (HMR)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Este es el SUPERPOWER de Vite:"
echo ""
echo -e "${YELLOW}Prueba 1 - Editar estilos en tiempo real${NC}"
echo "  1. Abre: resources/js/components/App.css"
echo "  2. Cambia el color del gradiente (línea ~1):"
echo "     De: background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);"
echo "     A:  background: linear-gradient(135deg, #ff6b6b 0%, #4ecdc4 100%);"
echo "  3. Guarda el archivo"
echo "  4. ${GREEN}¡El navegador se actualiza AUTOMÁTICAMENTE sin perder el estado!${NC}"
echo ""

echo -e "${YELLOW}Prueba 2 - Editar texto en tiempo real${NC}"
echo "  1. Abre: resources/js/components/App.jsx"
echo "  2. Cambia la línea con: <h1>¡Hola desde React! 🚀</h1>"
echo "  3. Guarda el archivo"
echo "  4. ${GREEN}El navegador se actualiza al instante${NC}"
echo ""

echo -e "${BLUE}PASO 6: Solucionar problemas comunes${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo -e "${RED}❌ Error: 'Could not find a match for laravel/laravel'${NC}"
echo "  Solución:"
echo "    \$ rm -rf node_modules package-lock.json"
echo "    \$ npm install"
echo ""

echo -e "${RED}❌ Error: 'Port 8000 already in use'${NC}"
echo "  Solución:"
echo "    \$ php artisan serve --port=8001"
echo ""

echo -e "${RED}❌ Página en blanco en http://localhost:8000/react-app${NC}"
echo "  Solución:"
echo "    1. Verifica que npm run dev esté corriendo"
echo "    2. Abre Developer Tools (F12) → Console"
echo "    3. Busca errores en rojo"
echo "    4. Recarga la página (Ctrl+Shift+R para cache limpio)"
echo ""

echo -e "${RED}❌ Contador no funciona${NC}"
echo "  Solución:"
echo "    1. Verifica que app.jsx esté importando React"
echo "    2. Verifica que el div #react-app existe en react.blade.php"
echo "    3. Recarga la página"
echo ""

echo -e "${BLUE}PASO 7: Verifica la consola de desarrollo${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "En el navegador:"
echo "  1. Presiona F12 o Ctrl+Shift+I"
echo "  2. Ve a la pestaña 'Console'"
echo "  3. NO debe haber errores en rojo"
echo "  4. Deberías ver mensajes de Vite"
echo ""

echo -e "${BLUE}PASO 8: Información de los archivos clave${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📄 resources/js/app.jsx"
echo "   • Entry point de React"
echo "   • Busca el elemento #react-app"
echo "   • Monta el componente App"
echo ""
echo "📄 resources/js/components/App.jsx"
echo "   • Componente principal"
echo "   • Contiene el estado (contador)"
echo "   • Define los 3 botones"
echo ""
echo "📄 resources/js/components/App.css"
echo "   • Estilos del componente"
echo "   • Gradiente, colores de botones"
echo "   • Responsive para móvil"
echo ""
echo "📄 resources/views/react.blade.php"
echo "   • Plantilla Blade de Laravel"
echo "   • Carga CSS y JS vía @vite()"
echo "   • Contiene el div #react-app"
echo ""

echo -e "${BLUE}RESUMEN RÁPIDO${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  ${YELLOW}Terminal 1:${NC} php artisan serve"
echo "  ${YELLOW}Terminal 2:${NC} npm run dev"
echo "  ${YELLOW}Navega a:${NC} http://localhost:8000/react-app"
echo "  ${YELLOW}Prueba:${NC} Los 3 botones del contador"
echo "  ${YELLOW}Edita:${NC} Los archivos .jsx y .css para ver HMR en vivo"
echo ""
echo -e "${GREEN}¡Listo para probar!${NC}"
echo ""
