#!/bin/bash

# Colores para el output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}"
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║          🌴 COSTA RICA TRIP PACKAGES - PROYECTO LISTO 🌴       ║"
echo "║              Laravel + React + Vite + Blade SEO                ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

echo -e "${GREEN}✓ Proyecto creado exitosamente${NC}\n"

echo -e "${BLUE}📋 ESTADO DEL PROYECTO:${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "  ✅ Laravel 11 instalado"
echo -e "  ✅ PHP 8.1 configurado"
echo -e "  ✅ React 19 instalado"
echo -e "  ✅ Vite 5 configurado"
echo -e "  ✅ Landing page Blade (SEO optimizada)"
echo -e "  ✅ Componente React Hello World interactivo"
echo -e "  ✅ Build estático generado (52KB)"
echo -e "  ✅ Listo para Hostinger Premium"
echo ""

echo -e "${BLUE}🚀 COMANDOS PARA INICIAR EN DESARROLLO:${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${YELLOW}Terminal 1 - Servidor Laravel:${NC}"
echo "  cd /home/elizabeth/costaricatrippackages"
echo "  php artisan serve"
echo ""
echo -e "${YELLOW}Terminal 2 - Vite (Hot Module Reload):${NC}"
echo "  cd /home/elizabeth/costaricatrippackages"
echo "  npm run dev"
echo ""

echo -e "${BLUE}🌐 PÁGINAS DISPONIBLES:${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "  ${GREEN}Landing Page:${NC} http://localhost:8000/"
echo "    → Blade puro con HTML/CSS"
echo "    → Optimizado para SEO"
echo "    → Muestra paquetes turísticos"
echo ""
echo -e "  ${GREEN}React App:${NC} http://localhost:8000/react-app"
echo "    → Componente React interactivo"
echo "    → Contador con 3 botones"
echo "    → Información de la estructura"
echo ""

echo -e "${BLUE}📦 PRODUCCIÓN (Hostinger Premium):${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${YELLOW}Paso 1 - Generar build estático:${NC}"
echo "  npm run build"
echo ""
echo -e "${YELLOW}Paso 2 - Subir a Hostinger (vía FTP/SFTP):${NC}"
echo "  ✓ public/          (incluye build/)"
echo "  ✓ app/"
echo "  ✓ routes/"
echo "  ✓ resources/views/"
echo "  ✓ .env"
echo "  ✓ composer.json"
echo "  ✗ node_modules/    (NO subir)"
echo ""
echo -e "${YELLOW}Paso 3 - En servidor Hostinger:${NC}"
echo "  composer install --no-dev"
echo "  php artisan key:generate"
echo "  chmod 755 storage/ bootstrap/cache/"
echo ""

echo -e "${BLUE}📁 ESTRUCTURA DEL PROYECTO:${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "resources/"
echo "├── js/"
echo "│   ├── app.jsx                  ← Entry point React"
echo "│   └── components/"
echo "│       ├── App.jsx              ← Componente principal"
echo "│       └── App.css              ← Estilos"
echo "│"
echo "└── views/"
echo "    ├── landing.blade.php        ← Landing page"
echo "    └── react.blade.php          ← App React"
echo ""
echo "public/"
echo "└── build/                       ← Build estático (generado)"
echo "    ├── assets/"
echo "    │   └── app-*.js             ← JavaScript compilado"
echo "    └── manifest.json            ← Manifest de Vite"
echo ""

echo -e "${BLUE}🔧 STACK TECNOLÓGICO:${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "  🐘 PHP 8.1"
echo -e "  🌱 Laravel 11"
echo -e "  ⚛️  React 19"
echo -e "  ⚡ Vite 5"
echo -e "  🎨 Blade Templates"
echo -e "  💻 Modern JavaScript (ES6+)"
echo ""

echo -e "${BLUE}📚 DOCUMENTACIÓN:${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "  📄 ESTRUCTURA.md    → Detalles técnicos completos"
echo -e "  📄 README_SETUP.md  → Guía de configuración"
echo ""

echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✓ PROYECTO COMPLETADO Y LISTO PARA USAR ${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
